[server]
bind_addr = "0.0.0.0:2087"
transport = "quic"
token = "mehdi"
web_port = 2526
log_level = "info"

[[server.ports]]
address = "0.0.0.0:2096"
target = "127.0.0.1:2096"
type = "udp"

[[server.ports]]
address = "0.0.0.0:50961"
target = "127.0.0.1:50961"
type = "udp"

[[server.ports]]
address = "0.0.0.0:2083"
target = "127.0.0.1:2083"
type = "tcp"

[[server.ports]]
address = "0.0.0.0:40960"
target = "127.0.0.1:40960"
type = "tcp"
